@Fuxion.Ali.API_HostAddress = https://localhost:7029

POST {{Fuxion.Ali.API_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "userName": "admin",
  "password": "admin"
}
###

GET {{Fuxion.Ali.API_HostAddress}}/api/user?search=
