<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>44b7f491-b7af-4726-9402-d7bc73250157</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
	<PackageReference Include="Fuxion.Ali.Contracts" Version="1.0.1-feature-auth.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fuxion.Ali.Application\Fuxion.Ali.Application.csproj" />
    <ProjectReference Include="..\Fuxion.Ali.Infrastructure\Fuxion.Ali.Infrastructure.csproj" />
  </ItemGroup>

</Project>
